# Created with YamlCreate.ps1 v2.2.10 $debug=NVS1.CRLF.5-1-22621-2506.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: BSG.Launcher
PackageVersion: 13.0.2.2031
InstallerLocale: en-US
InstallerType: exe
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT
  SilentWithProgress: /SILENT
  Custom: /NORESTART
UpgradeBehavior: install
ReleaseDate: 2016-08-04
Installers:
- Architecture: x64
  InstallerUrl: https://prod.escapefromtarkov.com/launcher/download
  InstallerSha256: 6CAB4296366E23C20186C8A59CE40BCD06D2633ACC657860E3510CB9EFBC022A
  ProductCode: CF8E6E00-9C03-4440-81C0-21FACB921A6B
ManifestType: installer
ManifestVersion: 1.5.0
